### ISSUE TITLE
HTMLでの画像の表示方法

### ISSUE THREAD

**Issue by yamauch** [p2hacks/teamR08#24]
ろうえね早く教えて

**Comment by lowene** [comment]
えーと画像の大きさの変更だっけ？（寝て忘れた顔）

**Comment by yamauch** [comment]
それと、ふたつならべるほうほう！

**Comment by lowene** [comment]
二つ並べる方法はいくつかあると思うけど俺は「とりあえず実装」の精神で、画像の位置を変えた
hoge.css
.className{
 width:100px;（幅をかえる、50%などもある）
 height:100px;（高さを変える、以下同分）
 top:100px; （画像を表示させる高さをかえる、bottomでも可能）
 left:100px;　（画像を表示する幅って言うのかな…ｘ軸みたいな、所を変えれる、rightでも可能）
}

**Comment by yamauch** [comment]
なるほど、ちょい試してみる
