### ISSUE TITLE
画像のトリミングについて

### ISSUE THREAD

**Issue by lowene** [p2hacks/teamR08#25]
画像の不要な背景の白かったりするところを何とかなくしたい
俺の入れてあるスマホアプリでなんとかなるかもしれない
現在スマホを家に忘れているのでわからんが

**Comment by yamauch** [comment]
スマホアプリ最近優秀だからいけなくもない保存したときワンチャン透過したところがおかしくなるかも

**Comment by lowene** [comment]
取りあえず試す

**Comment by lowene** [comment]
携帯アプリの奴、ダメだった
