### ISSUE TITLE
画像を配列に格納させたい

### ISSUE THREAD

**Issue by yamauch** [p2hacks/teamR08#26]
画像を配列に格納させたいです

**Comment by lowene** [comment]
import X from './images/hoge1.jpg';//画像を取得
import Y from './images/hoge.jpg';//同じく
var images = new Array(X,Y);//画像をimportした変数を入れた配列の宣言
function App(){
  return(
    <img src={images[0]}></img>
  );
}

こんな感じです、伝わりますか？

**Comment by lowene** [comment]
ごめんなんかばぐった
return(
  <img src={images0]>
  );
こう書きたかった、</img>まで書くとダメなのかも

**Comment by lowene** [comment]
バグったので再掲

return() のなかで img タグの src 属性で images[0] や images[1] を入れても表示されます

**Comment by yamauch** [comment]
ありがと！！！
今から風呂入るから上がったらやってみるね！
