### ISSUE TITLE
個人目標かいてくださいな

### ISSUE THREAD

**Issue by yamauch** [p2hacks/teamR08#3]

**Comment by shu-holly** [comment]
forkにcommitした後に、元のリポジトリにプルリクすることで、元のリポジトリにmergeできるようです。

**Comment by yamauch** [comment]
ほ、ほほう？？詳しい話はまた明日聞きますね！！

**Comment by lowene** [comment]
個人目標：フロントエンドを学びなからアプリ製作をしていき、さらにその中でアプリ製作そのものやGitなどの使い方を学ぶ

**Comment by yamauch** [comment]
神
